version: '3.9'
services:
  resourcedb:
    restart: always
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=${RESOURCE_POSTGRES_DB}
      - POSTGRES_USER=${RESOURCE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${RESOURCE_POSTGRES_PASSWORD}
    ports:
      - '5000:5432'
    volumes:
      - resourcedb:/var/lib/postgresql/data

  authdb:
    restart: always
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
    ports:
      - '5001:5432'
    volumes:
      - authdb:/var/lib/postgresql/data

  api:
    restart: always
    environment:
      - RESOURCE_DB_CONNECTION_URI
      - GIGAMONO_CONFIG_FILE
      - AUTH_PUBLIC_KEY
    build:
      context: ../../../
      dockerfile: gigamono/docker/gigamono-api/Dockerfile
    ports:
      - '3010:3010'
    depends_on:
      - resourcedb
      - auth

  auth:
    restart: always
    environment:
      - AUTH_DB_CONNECTION_URI
      - GIGAMONO_CONFIG_FILE
      - AUTH_PRIVATE_KEY
      - AUTH_PUBLIC_KEY
    build:
      context: ../../../
      dockerfile: gigamono/docker/gigamono-auth/Dockerfile
    ports:
      - '3020:3020'
    depends_on:
      - authdb

volumes:
  resourcedb:
  authdb:
